### ISSUE TITLE
[telas] (25 mangos) Corrigir a tela de Menu

### ISSUE THREAD

**Issue by fegemo** [fegemo/cefet-games-meow-au#116]
A tela de menu, feita na estória #54, foi criada sem utilizar os recursos do pacote `scene2d.ui`, conforme solicitado. Além disso, o posicionamento dos elementos do menu foi feito usando números absolutos, o que faz com que os botões apareçam em posições incorretas em tamanhos de telas diferentes.

Faz parte desta estória corrigir esse problema, refatorando o código da tela para usar os recursos de criação de interfaces do pacote `scene2d.ui`.

Pode-se ganhar mangos bônus ao dar uma suculentada nessa tela. Por exemplo, fazer os botões surgirem **sutilmente** em vez de eles ficarem completamente parados lá, assim que se entra na tela e assim que se clica em "jogar" (e aí mostra os modos campanha e survival).

**Comment by fegemo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#116 Corrigir a tela de Menu](https://trello.com/c/sMDbXpkv/45-116-corrigir-a-tela-de-menu)

**Comment by andrebrait** [comment]
Já corrigi o posicionamento. Falta os botões surgirem suavemente e etc.

Estou corrigindo isso junto do fade quando maximizado (que fica só um quadradinho) e o Heisenbug também.

**Comment by fegemo** [comment]
Beleza. Você está usando o `scene2d.ui`, certo?

**Comment by andrebrait** [comment]
Irei utilizar.

**Comment by andrebrait** [comment]
Completada a transição para o scene2d.ui. Que API boazinha.

~~Que tipo de suculentada você pensa para os botões surgirem e sumirem suavemente? Um fade, por exemplo?~~

**Comment by andrebrait** [comment]
Acabei de adicionar efeitos de transição para os botões e afins na tela.
