### ISSUE TITLE
[telas] (20 mangos) Aprimorar a tela de créditos

### ISSUE THREAD

**Issue by fegemo** [fegemo/cefet-games-meow-au#122]
A tela de créditos #55 contém um texto que vai passando automaticamente sem o controle do usuário. Não é possível alterar a velocidade do texto (ele pode estar rápido demais, por exemplo), nem sair da tela antes que o texto tenha terminado de passar. Isso não é bom para o usuário.

A ideia desta estória é alterar a tela pra usar componentes da `scene2d.ui` - por exemplo, um `Label` com o texto, dentro de um `ScrollPane` - para permitir que o próprio usuário possa rolar o texto, além de colocar um botão para voltar à tela de menu principal.

Por fim, melhorar um pouco o texto dos créditos... nós não somos **colaboradores**, somos os **desenvolvedores**, os **artistas**, os **game designers**, os **músicos** etc. E também colocar algo como "Feito com amor S2S2 pela turma de Desenvolvimento de Jogos do CEFET-MG em 2017/02".

**Comment by fegemo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#122 Aprimorar a tela de Créditos](https://trello.com/c/qPhqJSr7/47-122-aprimorar-a-tela-de-cr%C3%A9ditos)

**Comment by andrebrait** [comment]
Solução no PR #124
