### ISSUE TITLE
[bug] (20 mangos) Problemas na tela de pause

### ISSUE THREAD

**Issue by andrebrait** [fegemo/cefet-games-meow-au#125]
Pausar durante a tela de pré-jogo não pára a música, porém para a tela.
Pausar durante os jogos pode fazer com que o ícone de voluma persista na tela.

Será necessário verificar todos os minigames.

**Comment by fegemo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#125 Corrigir problemas na pausa](https://trello.com/c/4dX9REvl/48-125-corrigir-problemas-na-pausa)
