### ISSUE TITLE
[game-design] Consertar MiniGame TheFridgeGame

### ISSUE THREAD

**Issue by fegemo** [fegemo/cefet-games-meow-au#40]
Para recuperar a nota perdida no TP1, neste MiniGame:

- (3%) "city-shopping.mp3" deveria ser uma Music (e não um Sound). A LibGDX trata as duas coisas diferentemente: Music é para arquivos grandes, Sound é para efeitos sonoros (curtos). Este é um bug crítico.
- (3%) As partes da geladeira "tremem" no início, quando o jogo está começando (seria um problema de arredondamento?

Desenvolvedores com preferência: Estevão e Sarah

**Comment by sarahrms** [comment]
Resolvido o problema da música e da geladeira tremendo.
