### ISSUE TITLE
[programação] (25 mangos) Ligar/desligar o áudio

### ISSUE THREAD

**Issue by fegemo** [fegemo/cefet-games-meow-au#71]
O grupo deve criar um botão para ligar/desligar o áudio inteiro do jogo. Esse botão deve ser visível na tela de splash, na de menu e na tela de jogo - neste último caso, quando o usuário clicar no botão pause, um menu irá aparecer (criado na tarefa #70 - botão voltar ao menu quando pausa) e ele deve conter a funcionalidade para ligar/desligar o áudio.

**Comment by fegemo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#71 Ligar/desligar o áudio (2ª sprint)](https://trello.com/c/vRwO9KU6/38-71-ligar-desligar-o-%C3%A1udio-2-sprint)

**Comment by luizaas** [comment]
O botão esta funcionando a partir da tela de menu, porem ao retirar o som e retornar ao menu inicial os ícones de com som e sem som sao invertidos. Estou com dificuldade para resolver este bug, porém nao acredito que seja critico
